[opener]
xournalpp = [
  { run = 'xournalpp "$@"', orphan = true, for = "unix"},
]
pdf = [
  { run = 'evince "$@"', orphan = true, for = "unix"},
]

[open]
prepend_rules = [
  { name = "*.xopp", use = "xournalpp"},
  { name = "*.pdf", use = "pdf"},
]
