[manager]
prepend_keymap = [
  { on = ["c", "p"], run = '''shell 'blobdrop "$1"' --confirm''', desc = "copy and paste" },
  { on = ["K"], run = "arrow -5", desc = "Move up 5 lines" },
  { on = ["J"], run = "arrow 5", desc = "Move down 5 lines" },
]
