{ config, pkgs, ... }:
{
programs.steam = {
  enable = true;
  remotePlay.openFirewall = true; # Open ports in the firewall for Steam Remote Play
  dedicatedServer.openFirewall = true; # Open ports in the firewall for Source Dedicated Server
  localNetworkGameTransfers.openFirewall = true; # Open ports in the firewall for Steam Local Network Game Transfers
};
  environment.systemPackages = with pkgs; [
    mesen
    python3
    uv
    #google-drive-ocamlfuse
    #drive
    rclone
    arduino-ide
    #chromium
    #steam
    protontricks
    #anki
    texstudio
    texlive.combined.scheme-full
    lyx
    #haskell-ci
    dbus
    vim
    neovim
    vim-language-server
    emacs
    gcc
    git
    #pcmanfm
    wget
    alacritty
    #ddgr
    vivaldi
    xournalpp
    krita
    libreoffice
    flameshot
    obsidian
    evince
    kdePackages.okular
    onboard
    unar
    poppler_utils
    xclip
    blobdrop
    yazi
    zsh
    zsh-autosuggestions
    #zsh-autocompletion
    R
    rstudio
    light
    #firefox
    #sl
    #ripdrag
    dragon
    exiftool
    #ffmpeg
    vscode
    brightnessctl
    anki
    #wl-clipboard
    #wvkbd
    #squeekboard
    #xkbd
    #google-chrome
    #home-manager
    coq_8_9
    rnote
    snes9x
    wla-dx
    gnumake
    nomacs
    gwenview
    digikam
    nsxiv
    shotwell
    xkeysnail
    zsnes2
    obs-studio
    nodejs
  ];
}
